---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: clock-trigger-java
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: clock-synchronization
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: clock-synchronization-java
