---
kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: dynamic-html-java
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: 5m
    spec:
      containers:
        - image: fusion-108:5000/dynamic-html:native
          name: benchmark
          env:
            - name: TYPE
              value: "printRetValTypeD"
