---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: dynamic-html-trigger-java
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: dynamic-html
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: dynamic-html-java
