---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: graph-pagerank-trigger-java
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: graph-pagerank
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: graph-pagerank-java
