---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: server-reply-trigger-java
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: server-reply
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: server-reply-java
