---
kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: sleep-java
spec:
  template:
    metadata:
      labels:
        apps: benchmark
    spec:
      containers:
        - image: fusion-108:5000/sleep:native
          name: benchmark
          env:
            - name: TYPE
              value: sleep
