---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: thumbnailer-trigger-java
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: thumbnailer
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: thumbnailer-java
