apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: fusion-108:5000/gcr.io/knative-samples/helloworld-go
          env :
            - name: TARGET
              value: "Knative + Istio"
