apiVersion: v1
kind: Secret
metadata:
  name: cos
type: Opaque
stringData:
  keyId: bWluaW9hZG1pbg==        # e.g., "AKIAXXXXXXXXXXXXXXXX"
  secretKey: bWluaW9hZG1pbg==  # e.g., "wJalrXUtnFEMI/K7MDENG/bPxRfiCYXXXXXX"
