# minio-values.yaml
image:
  repository: intel-112:5000/quay.io/minio/minio
  tag: RELEASE.2024-04-18T19-09-19Z
  pullPolicy: IfNotPresent

mode: distributed
replicas: 10  # 10 replicas (pods)
pool:  # Spread across labeled nodes
  nodeSelector:
    node_type: fusion
  tolerations:
    - key: "node_type"
      operator: "Equal"
      value: "fusion"
      effect: "NoSchedule"
  volumeClaimTemplate:  # Custom PVC template
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: fusion-110-nfs-storage
    volumeMode: Filesystem

rootUser: minioadmin
rootPassword: minioadmin

persistence:
  enabled: true
  size: 20Gi  # Matches PVC request
  storageClass: fusion-110-nfs-storage

resources:
  requests:
    cpu: 1
    memory: 2Gi
